### ISSUE TITLE
AOL and double quotes in a CSS selector

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#1]
Using double quotes in a CSS selector completely messes up with AOL desktop webmail's parser. The following example…
```css
[class="test"] { color:red; }
```
… becomes :
```css
.aolReplacedBody [class="
test"
] {
    color: red;
}
```
It gets even worse when combined with a pseudo class and multiple selectors for a same rule set. The following…
```css
.test:hover, [class="test"]:hover { color:red; }
```
…becomes : 
```css
test"
]:hover {
    color: red;
    .aolReplacedBody .test: hover,.aolReplacedBody [class="
}
```
