### ISSUE TITLE
Yahoo has a default style targeting [dir]

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#15]
The desktop webmail of Yahoo has a default style rule targeting any element with a `dir` attribute.

```css
[dir] {
     text-align:start;
}
```

Thus it breaks the cascade if you wanted to inherit `text-align` from a parent element. Any element with a `dir` attribute should also include a `text-align` style inline.

**Comment by husseinalhammad** [comment]
I don't see this anymore. But, I see the email message is rendered in `<li>` which has a default `text-align` value in Chrome's user agent stylesheet:

```css
li {
    text-align: -webkit-match-parent;
}
```

This cascades and it can affect the alignment of elements. For example, `body[dir=ltr] li p[dir=rtl]` will be unexpectedly aligned to the left.
