### ISSUE TITLE
AOL and background-image in a <style> tag

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#2]
AOL incorrectly replaces the path of a `background-image` when used in a `<style>` tag. It wraps the URL of the image with an `<a>` tag linking to the image itself. The following example…

``` css
<style type="text/css">
    .test {
        background-image:url("http://i.imgur.com/A4kblQ3.jpg");
    }
</style>
```

… becomes :

``` css
<style type="text/css">
    .test {
        background-image:url(&quot;<a href="http://i.imgur.com/A4kblQ3.jpg&quot" target=_blank>http://i.imgur.com/A4kblQ3.jpg&quot</a>;);
    }
</style>
```

The same thing happens if you use single quotes or no quotes at all. It happens with the `background-image` property and the `background` shorthand. It happens no matter if the `<style>` tag is in the `<body>` or the `<head>`.

It doesn't happen when using `background` or `background-image` inline in a `style` attribute.

**Comment by M-J-Robbins** [comment]
I'm finding it's affecting the following selector too.  In this example I just have 2 selectors ```form [lang=x-withform] ``` and ```form [lang=x-noform]``` 

```
.aolReplacedBody form [lang=x-withform] {
  display: block!important;
  background-image: url(<a href="https://api.rebelmail.com/v0/emails/55ca47ffd7d4fe1900a98b22/event.gif?type=variant&amp;variant=limited);
  max-height: none!important;
  overflow: visible!important
}

.aolReplacedBody" target=_blank>https://api.rebelmail.com/v0/emails/55ca47ffd7d4fe1900a98b22/event.gif?type=variant&amp;variant=limited);max-height:none!important;overflow:visible!important
}
.aolReplacedBody</a> form [lang=x-noform]{max-height:0;overflow:hidden
}
```

As a solution I've just separated the bg image into it's own selector and added this after it
```
.aolfix{
	aol:fix;
}
```

**Comment by hteumeuleu** [comment]
@M-J-Robbins I think this is more [related to this bug](https://github.com/hteumeuleu/email-bugs/issues/1). But it's a nice solution you got there.

**Comment by hteumeuleu** [comment]
This bug was reported on Twitter to [@aolmailhelp](https://twitter.com/hteumeuleu/status/633369723275640832) and [@aolmail](https://twitter.com/advenix/status/633400047019757568).

**Comment by M-J-Robbins** [comment]
Yeah saw that, wan't aware of that before good catch.  But I wasn't using quotes (minify takes them out for me).

**Comment by hteumeuleu** [comment]
It seems that this bug was fixed. Background images are no longer badly replaced in AOL.

**Comment by hteumeuleu** [comment]
This issue seems to [have reappeared](https://github.com/hteumeuleu/email-bugs/issues/58). Testing the initial sample of this post, the code becomes:

```css
 #yiv8940145174 .yiv8940145174test {
    background-image:url("<a href="https://ecp.yusercontent.com/mail?url=http%3A%2F%2Fi1.cmail20.com%2Fei%2Fy%2F27%2F262%2F17D%2F032355%2Fcsimport%2Fa4kblq3_0.jpg&t=1550766248&ymreqid=94544d5c-a0a0-c294-2f3c-eb0009010000&sig=SduUSLEF32_3Qqm9a27jSw--~C" class="linkified" target="_blank">https://ecp.yusercontent.com/mail?url=http%3A%2F%2Fi1.cmail20.com%2Fei%2Fy%2F27%2F262%2F17D%2F032355%2Fcsimport%2Fa4kblq3_0.jpg&t=1550766248&ymreqid=94544d5c-a0a0-c294-2f3c-eb0009010000&sig=SduUSLEF32_3Qqm9a27jSw--~C</a>");
} 
```

**Comment by hteumeuleu** [comment]
Thanks for Matthieu B. on Slack for the ping, this issue seems fixed now. The previous example is now turned into:

```css
#yiv7928140548 .yiv7928140548test {
    background-image: removedimage__36ec86c5-3c4c-4886-b98f-1ebe79db19e8__url(https://ecp.yusercontent.com/mail?url=http%3A%2F%2Fi1.cmail20.com%2Fei%2Fy%…mreqid=94544d5c-a0a0-c294-2fc6-190009010000&sig=xeBxM_yYh4d4H5JzhEXleA--~C)
}
```
