### ISSUE TITLE
Yahoo will ignore embedded css if it is directly preceded by a comment

### ISSUE THREAD

**Issue by lheise** [hteumeuleu/email-bugs#25]
**Example:** 

`ul { padding: 0; }` was ignored. Yahoo added its `.undoreset ul { padding-left: 40px; }`

```css
body {
    font-family: Helvetica, Arial, sans-serif;
    font-size: 12px;
    color: #333333;
    line-height: 16px;
  }
/*comment in code*/
  ul {
    padding: 0; 
    margin: 0 0 0 15px;
  }

  ul ul { margin: 0 0 5px 15px; }
  li { margin: 0 0 5px 0; }`
```

**Corrected example:**

Once the comment has been removed, the `ul { padding: 0; }` will be respected.

```css
body {
    font-family: Helvetica, Arial, sans-serif;
    font-size: 12px;
    color: #333333;
    line-height: 16px;
  }

  ul {
    padding: 0; 
    margin: 0 0 0 15px;
  }

  ul ul { margin: 0 0 5px 15px; }
  li { margin: 0 0 5px 0; }`
```
