### ISSUE TITLE
The old Outlook.com doesn't prefix certain classes or ids (like "button", "menu", …)

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#3]
Outlook.com usually prefixes classes and ids used in HTML by `ecx`. It then adjust selectors used in a `<style>` tag accordingly (prefixing every rule by a `.ExternalClass` class). However, for certain names, the prefixing doesn't work in HTML, but happens in CSS, thus creating inoperative rules. I've noticed this happens with the following names : 
- button
- menu
- label
- nav

So for example if we have the following code :

``` css
<style type="text/css">
    .test,
    #test,
    .button,
    .menu,
    .label,
    .nav,
    #button,
    #menu,
    #label,
    #nav {
        padding:1em 1.5em;
        color:#fff;
        background:#2ecc40;
    }
</style>
<div class="test">.test</div>
<div id="test">#test</div>
<div class="button">.button</div>
<div id="button">#button</div>
<div class="menu">.menu</div>
<div id="menu">#menu</div>
<div class="label">.label</div>
<div id="label">#label</div>
<div class="nav">.nav</div>
<div id="nav">#nav</div>
```

… will be transformed by Outlook.com into this : 

``` css
<style type="text/css">
    .ExternalClass .ecxtest,
    .ExternalClass #ecxtest,
    .ExternalClass .ecxbutton,
    .ExternalClass .ecxmenu,
    .ExternalClass .ecxlabel,
    .ExternalClass .ecxnav,
    .ExternalClass #ecxbutton,
    .ExternalClass #ecxmenu,
    .ExternalClass #ecxlabel,
    .ExternalClass #ecxnav {
        padding:1em 1.5em;
        color:#fff;
        background:#2ecc40;
    }
</style>
<div class="ecxtest">.test</div>
<div id="ecxtest">#test</div>
<div class="button">.button</div>
<div id="button">#button</div>
<div class="menu">.menu</div>
<div id="menu">#menu</div>
<div class="label">.label</div>
<div id="label">#label</div>
<div class="nav">.nav</div>
<div id="nav">#nav</div>
```

This happens in Outlook.com on both the desktop and mobile webmail versions.
