### ISSUE TITLE
SFR adds grey background to <a> tags inside <th>

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#33]
The [desktop webmail of SFR](https://webmail.sfr.fr/) has annoying default styles applying to `<a>` tags inside `<th>`. It adds a grey background, sets the color in white and adds a right padding of 20px. Here are the incriminating styles:

```css
th a, th a:link, th a:visited {
	color: #fff;
	background: #808080;
	padding-right: 20px;
}
```

The styles can be found in SFR's [main.css](https://msc02.s-sfr.fr/fr_FR/20170615172601/css/main.css) file. Here's an example shared by someone (_sorry I can't remember who_) last october on the #emailgeeks slack.

![An example of grey boxes appearing after a inside th on SFR's webmail](https://i.imgur.com/sbjAuWN.png)

These default styles can be reset within an HTML email by including the following styles:

```css
th a, th a:link, th a:visited {
	color: initial;
	background: initial;
	padding-right: initial;
}
```
