### ISSUE TITLE
The old Outlook.com on mobile doesn't include the class it prefixes styles with

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#4]
Outlook.com, on both mobile and desktop, prefixes every CSS rules by `.ExternalClass`. This works great on desktop. However, on mobile, the `ExternalClass` is nowhere to be found anywhere in the HTML. This makes every CSS rule inoperative on mobile.

So for example, the following rule : 

``` css
<style type="text/css">
    .test  {
        padding:1em 1.5em;
        color:#fff;
        background:#2ecc40;
    }
</style>
<div class="test">Test</div>
```

… becomes :

``` css
<style type="text/css">
    .ExternalClass .ecxtest  {
        padding:1em 1.5em;
        color:#fff;
        background:#2ecc40;
    }
</style>
<div class="ecxtest">Test</div>
```

This works great on desktop because the email is wrapped by a `<div class="ExternalClass MsgBodyContainer">`. On mobile, the email is wrapped by a `<div class="mv_body" id="mv_body0">`. This wrapper (or any of its parent element) should also have the `ExternalClass` class.

**Comment by hteumeuleu** [comment]
This only happens in the old Outlook.com. The new Outlook.com / Office 365 doesn't have this bug.

**Comment by hteumeuleu** [comment]
The newer version of Outlook.com doesn't have this bug. The old Outlook.com should be completely obsolete, so I'm closing this bug.

**Comment by revelt** [comment]
I just checked the whatever Microsoft now calls UK hotmail account (things are changing perpetually) — there are no signs of `.ExternalClass` being used on the UI.

Also wanted to post here that an old fix to make Hotmail to display emails full-width:

```css
.ExternalClass {width:100%;}
```

and an old fix to force Hotmail to display normal line spacing:

```css
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}
```

It is a current best practice to remove any `.ExternalClass` instances from your templates.
