### ISSUE TITLE
Yahoo used to incorrectly filters media queries

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#49]
For historical purposes and future references, I'm archiving here an old Yahoo bug. Up until March 2015, the desktop webmail of Yahoo didn't support media queries. But Yahoo incorrectly filtered media queries, removing anything between the first opening accolade of a media query and the first closing accolade of the first rule inside the media query. It thus leave other styles in the media query applicable for any media.

Here's an example. Given the following code:

```css
.box {
	width:600px;
}

@media only screen and (max-width:600px) {
	.box {
		width:auto;
	}

	.box-title {
		font-size:1.25em;
	}
}
```

Yahoo would filter it like this:

```css
#yiv6851014585 .yiv6851014585box {
	width:600px;
}

_filtered #yiv6851014585 {
}

	#yiv6851014585 .yiv6851014585box-title {
		font-size:1.25em;
	}
}
```

(Notice how the rule `.box-title` is now outside of a media query and thus applicable anywhere.)

A solution widely shared was to use attributes selectors in CSS instead (like `[class="box"] instead of `.box`). The desktop webmail of Yahoo didn't support them either, thus filtering them and not applying them anywhere.

The following example…

```css
.box {
	width:600px;
}

@media only screen and (max-width:600px) {
	*[class="box"] {
		width:auto;
	}

	*[class="box-title"] {
		font-size:1.25em;
	}
}
```

…would be filtered by Yahoo into:

```css
#yiv6851014585 .yiv6851014585box {
	width:600px;
}

_filtered #yiv6851014585 {
}

	#yiv6851014585 * .filtered99999 {
		font-size:1.25em;
	}
}
```

This was also widely [documented and fixed thanks to Fresh Inbox](http://freshinbox.com/blog/yahoo-mail-fixes-media-query-bug-yahoo/) who [documented](http://freshinbox.com/articles/yahoo-sanitizer-bug.html) and reported the bug at the time.
