### ISSUE TITLE
Internet Explorer incorrectly interprets media queries when loading an email in SFR

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#5]
When opening an email in the french webmail of SFR ([http://webmail.sfr.fr](http://webmail.sfr.fr)) in Internet Explorer, it looks like all media queries behave unexpectedly. But if we resize the window, even by just one pixel, everything goes back to normal. I reproduced this bug in Internet Explorer 10 and 11 on Windows 8.1. 

Here's a test example : 

```css
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<title>SFR Media Query Bug</title>
	<style type="text/css">
		body { font:1em/1.5 sans-serif; margin:1.5em; background:#fff; }
		div { padding:1em 1.5em; margin-bottom:1.5em; background:#FF4136; }

		@media (max-width:320px) {
			body { padding:0; }
			.mq-maxwidth320 { color:#fff; background:#2ecc40; }
		}

		@media only screen and (max-width:320px) {
			body { padding:0; }
			.mq-onlyscreen-maxwidth320 { color:#fff; background:#2ecc40; }
		}

		@media (min-width:0) and (max-width:320px) {
			body { padding:0; }
			.mq-minwidth0-maxwidth320 { color:#fff; background:#2ecc40; }
		}

		@media only screen and (min-width:0) and (max-width:320px) {
			body { padding:0; }
			.mq-onlyscreen-minwidth0-maxwidth320 { color:#fff; background:#2ecc40; }
		}

		@media (min-width:1024px) {
			body { padding:0; }
			.mq-minwidth1024 { color:#fff; background:#2ecc40; }
		}

		@media only screen and (min-width:1024px) {
			body { padding:0; }
			.mq-onlyscreen-minwidth1024 { color:#fff; background:#2ecc40; }
		}
	</style>
</head>
<body>
	<div class="mq-minwidth0-maxwidth320">
		@media (min-width:0px) and (max-width:320px)
	</div>
	<div class="mq-onlyscreen-minwidth0-maxwidth320">
		@media only screen and (min-width:0px) and (max-width:320px)
	</div>
	<div class="mq-maxwidth320">
		@media (max-width:320px)
	</div>
	<div class="mq-onlyscreen-maxwidth320">
		@media only screen and (max-width:320px)
	</div>
	<div class="mq-minwidth1024">
		@media (min-width:1024px)
	</div>
	<div class="mq-onlyscreen-minwidth1024">
		@media only screen and (min-width:1024px)
	</div>
</body>
</html>
```

Here's the render on load : 
[![SFR bug on load in IE](http://i.imgur.com/X7W3j1ql.jpg)](http://i.imgur.com/X7W3j1q.jpg)

And here's the render after resizing the window : 
[![SFR bug after resize in IE](http://i.imgur.com/dtg7Dxul.jpg)](http://i.imgur.com/dtg7Dxu.jpg)
