### ISSUE TITLE
La Poste's mobile webmail default styles

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/email-bugs#51]
The [mobile webmail of french provider La Poste](https://m.laposte.net/) has a generic style rule that resets `width` on all elements.

```css
.email__body-content * {
width: auto !important;
}
```

One possible solution to override this is to add an `!important` on inline declarations as well. But because this would not work in Outlook 2007-2019, you'd need to add the `width` property twice, as such:

```html
<div style="width:50%; width:50% !important;"></div>
```
